name: date_plugin
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  date_plugin_android:
    path: ../date_plugin_android
  date_plugin_ios:
    path: ../date_plugin_ios
  date_plugin_linux:
    path: ../date_plugin_linux
  date_plugin_macos:
    path: ../date_plugin_macos
  date_plugin_web:
    path: ../date_plugin_web
  date_plugin_windows:
    path: ../date_plugin_windows
  date_plugin_platform_interface:
    path: ../date_plugin_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  plugin_platform_interface: ^2.1.8

flutter:
  plugin:
    platforms:
      android:
        default_package: date_plugin_android
      ios:
        default_package: date_plugin_ios
      linux:
        default_package: date_plugin_linux
      macos:
        default_package: date_plugin_macos
      web:
        default_package: date_plugin_web
      windows:
        default_package: date_plugin_windows